//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamCongVN_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advance
    {
        public int AdvanceID { get; set; }
        public int EmployeeID { get; set; }
        public string Reason { get; set; }
        public System.DateTime AdvanceDate { get; set; }
        public double Amount { get; set; }
        public string Signer { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
