//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamCongVN_BE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChamCongVNEntities : DbContext
    {
        public ChamCongVNEntities()
            : base("name=ChamCongVNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbsentApplications> AbsentApplications { get; set; }
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Advances> Advances { get; set; }
        public virtual DbSet<BonusSalary> BonusSalary { get; set; }
        public virtual DbSet<CheckIns> CheckIns { get; set; }
        public virtual DbSet<CheckOuts> CheckOuts { get; set; }
        public virtual DbSet<DeductionEmployees> DeductionEmployees { get; set; }
        public virtual DbSet<DegreeDetails> DegreeDetails { get; set; }
        public virtual DbSet<Degrees> Degrees { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<LaudatoryEmployees> LaudatoryEmployees { get; set; }
        public virtual DbSet<Levels> Levels { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<OverTimeApplications> OverTimeApplications { get; set; }
        public virtual DbSet<OverTimes> OverTimes { get; set; }
        public virtual DbSet<OvertimeSalary> OvertimeSalary { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Recruitments> Recruitments { get; set; }
        public virtual DbSet<RegulationEmployees> RegulationEmployees { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Salary> Salary { get; set; }
        public virtual DbSet<SalaryTable> SalaryTable { get; set; }
        public virtual DbSet<Shifts> Shifts { get; set; }
        public virtual DbSet<Specialities> Specialities { get; set; }
        public virtual DbSet<SpecialityDetails> SpecialityDetails { get; set; }
        public virtual DbSet<States> States { get; set; }
        public virtual DbSet<Works> Works { get; set; }
        public virtual DbSet<DegreesOfEmployee> DegreesOfEmployee { get; set; }
        public virtual DbSet<EmployeeForAccount> EmployeeForAccount { get; set; }
        public virtual DbSet<GetAllTimeKeeping> GetAllTimeKeeping { get; set; }
        public virtual DbSet<GetCountCheckedIn> GetCountCheckedIn { get; set; }
        public virtual DbSet<GetCountHaventCheckedIn> GetCountHaventCheckedIn { get; set; }
        public virtual DbSet<GetCountLates> GetCountLates { get; set; }
        public virtual DbSet<SpecialityOfEmployee> SpecialityOfEmployee { get; set; }
    }
}
