//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamCongVN_BE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChamCongVNEntities : DbContext
    {
        public ChamCongVNEntities()
            : base("name=ChamCongVNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbsentApplication> AbsentApplications { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Advance> Advances { get; set; }
        public virtual DbSet<AnotherCost> AnotherCosts { get; set; }
        public virtual DbSet<BonusSalary> BonusSalaries { get; set; }
        public virtual DbSet<CheckIn> CheckIns { get; set; }
        public virtual DbSet<CheckOut> CheckOuts { get; set; }
        public virtual DbSet<DeductionEmployee> DeductionEmployees { get; set; }
        public virtual DbSet<DegreeDetail> DegreeDetails { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<LaudatoryEmployee> LaudatoryEmployees { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<OTCheckIn> OTCheckIns { get; set; }
        public virtual DbSet<OTCheckOut> OTCheckOuts { get; set; }
        public virtual DbSet<OverTimeApplication> OverTimeApplications { get; set; }
        public virtual DbSet<OverTime> OverTimes { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Recruitment> Recruitments { get; set; }
        public virtual DbSet<RegulationEmployee> RegulationEmployees { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<SalaryTable> SalaryTables { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<Speciality> Specialities { get; set; }
        public virtual DbSet<SpecialityDetail> SpecialityDetails { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<TotalSalaryPerMonth> TotalSalaryPerMonths { get; set; }
        public virtual DbSet<Work> Works { get; set; }
        public virtual DbSet<DegreesOfEmployee> DegreesOfEmployees { get; set; }
        public virtual DbSet<EmployeeForAccount> EmployeeForAccounts { get; set; }
        public virtual DbSet<GetAllOTTimeKeeping> GetAllOTTimeKeepings { get; set; }
        public virtual DbSet<GetAllTimeKeeping> GetAllTimeKeepings { get; set; }
        public virtual DbSet<GetCountCheckedIn> GetCountCheckedIns { get; set; }
        public virtual DbSet<GetCountHaventCheckedIn> GetCountHaventCheckedIns { get; set; }
        public virtual DbSet<GetCountLate> GetCountLates { get; set; }
        public virtual DbSet<SalaryNoOvertimeSalary> SalaryNoOvertimeSalaries { get; set; }
        public virtual DbSet<SalaryPaidLeave> SalaryPaidLeaves { get; set; }
        public virtual DbSet<SpecialityOfEmployee> SpecialityOfEmployees { get; set; }
        public virtual DbSet<TotalOvertimeSalary> TotalOvertimeSalaries { get; set; }
        public virtual DbSet<TotalSalaryOfEmployee> TotalSalaryOfEmployees { get; set; }
    }
}
