//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamCongVN_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetAllOTTimeKeeping
    {
        public string EmployeeName { get; set; }
        public int EmployeeID { get; set; }
        public string Department { get; set; }
        public string OTCheckInImage { get; set; }
        public string OTCheckInStatus { get; set; }
        public string OTCheckInDevice { get; set; }
        public Nullable<System.DateTime> OTCheckInCreatedAt { get; set; }
        public string OTCheckOutImage { get; set; }
        public string OTCheckOutStatus { get; set; }
        public string OTCheckOutDevice { get; set; }
        public Nullable<System.DateTime> OTCheckOutCreatedAt { get; set; }
    }
}
