//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamCongVN_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialityDetails
    {
        public int SpecialityDetailID { get; set; }
        public int SpecialtyID { get; set; }
        public int EmployeeID { get; set; }
    }
}
