//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamCongVN_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalSalaryOfEmployee
    {
        public Nullable<int> EmployeeID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> TotalTime { get; set; }
        public double Salary { get; set; }
        public double TotalAdvance { get; set; }
        public double TotalDeduction { get; set; }
        public double TotalLaudatory { get; set; }
        public int TotalOvertime { get; set; }
        public double TotalOvertimeSalary { get; set; }
        public Nullable<double> TotalSalary { get; set; }
    }
}
